### PR TITLE
#226: Reference only accessible qualified methods

### LINKED ISSUE #226: References of `qualifiedByName` work for protected methods that are not accessible by mapstruct
Consider two mappers in separate packages, one of which uses the other.

```java
package demo.a;

import demo.b.CommonMapper;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper(uses = CommonMapper.class)
interface DemoMapper {

	@Mapping(target = "name", source = "name", qualifiedByName = "toUpperCase")
	Target map(Source source);

}

class Source {
	public String name;
}

class Target {
	public String name;
}
```

```java
package demo.b;

import org.mapstruct.Mapper;
import org.mapstruct.Named;

@Mapper
public abstract class CommonMapper {

	@Named("toUpperCase")
	protected String toUpperCase(String value) {
		return value.toUpperCase();
	}
}
```

Note that the method toUpperCase is protected and therefore not available for MapStruct to pick up. MapStruct  therefore correctly shows the error:
```
C:\...\src\main\java\demo\a\DemoMapper.java:10:5
java: Qualifier error. No method found annotated with @Named#value: [ toUpperCase ]. See https://mapstruct.org/faq/#qualifier for more info.
```

The plugin, however, has a clickable reference. This is the second time I've stumbled across that issue. It makes it difficult to identify the cause because you assume that if it works with the plugin, it should also work with the annotation processor.

The plugin should also consider the visibility of the referencing methods.

### PR DESCRIPTION
**Pull request by thunderhook**
Fixes #226

### CODE REVIEW

File: src/main/java/org/mapstruct/intellij/codeinsight/references/MapstructMappingQualifiedByNameReference.java [hunk 1]
```diff
@@ -113,12 +114,41 @@ private Stream<PsiMethod> findAllNamedMethodsFromThisAndReferencedMappers(@NotNu
         Stream<PsiMethod> internalMethods = Stream.of( containingClass.getMethods() )
             .filter( MapstructUtil::isNamedMethod );
```
Comment (filiphr) [inline src/main/java/org/mapstruct/intellij/codeinsight/references/MapstructMappingQualifiedByNameReference.java:115]: Shouldn't we filter out private methods here?

File: testData/completion/qualifiedbyname/MappingQualifiedByNameWithAllPossibleVisibilities.java [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+import org.mapstruct.helper.qualifiedbyname.external.ExternalMapper;
+
+@Mapper(uses = { ExternalMapper.class, SamePackageMapper.class })
+public interface CarMapper {
+
+    @Mapping(target = "make", qualifiedByName = "<caret>")
+    CarDto carToCarDto(Car car);
+
+    @Named("internalModifierPackagePrivate")
+    String internalModifierPackagePrivate(String value) {
```
Comment (filiphr) [inline testData/completion/qualifiedbyname/MappingQualifiedByNameWithAllPossibleVisibilities.java:23]: This is not an `internalModifier` this is public, due to the fact that `CarMapper` is an interface and not a class

**Review by filiphr — CHANGES_REQUESTED** [review]
Thanks @thunderhook. I've left some comments. It needs a bit more work.

Additionally, while reviewing it, I think that I realized that qualifiers on super types are not taken into consideration.

e.g. if we have

```java
@Mapper
interface CarMapper extends BaseMapper {
    //...
}
```

I think that we need to do `getAllMethods` instead of doing `getMethods`

File: src/main/java/org/mapstruct/intellij/codeinsight/references/MapstructMappingQualifiedByNameReference.java [hunk 3]
```diff
@@ -110,15 +111,45 @@ private Stream<PsiMethod> findAllNamedMethodsFromThisAndReferencedMappers(@NotNu
...
+            return false;
+        }
+
+        if ( method.hasModifierProperty( PsiModifier.PUBLIC ) ) {
+            return true;
+        }
+
+        if ( method.hasModifierProperty( PsiModifier.PROTECTED ) ) {
+            return methodClass.equals( containingClass );
+        }
```
[the remark this answers is not in the document]
Comment (thunderhook) [reply src/main/java/org/mapstruct/intellij/codeinsight/references/MapstructMappingQualifiedByNameReference.java]: Yes, you're right. I got confused by the table where _subclass_ and _no modifier_ says _N_ because our generated mappers are subclasses.
