### PR TITLE
#151 rework inheritance and support auto inheritance

### LINKED ISSUE #151: Rework `@InheritConfiguration` and support auto-inheritance
Followup of #65.

First: there is a wrong implementation because the plugin supports inheritance over referenced mappers (`uses=...`), which is not supported, see `CarMapperWithExplicitInheritance` in the mapstruct project.

Second: the `MappingInheritanceStrategy.AUTO_INHERIT_*`  options of ` @MapperConfig` are not supported yet. Therefore you see warnings/errors that are simply wrong.

So I rewrote the whole inheritance logic and followed the code that implemented it in the mapstruct main project. I copied some of the code to be consistent with the original mapstruct code. I also commented where to find the logic in the mapstruct project (for the case they get a proper refactoring...)

### PR DESCRIPTION
**Pull request by thunderhook**
See #151. This took me a while to figure out how the inheritance is handled by MapStruct.

Fixes #151

### CODE REVIEW

File: src/main/java/org/mapstruct/intellij/util/MapstructAnnotationUtils.java [hunk 1]
```diff
@@ -314,7 +314,7 @@ else if ( mappingsValue instanceof PsiAnnotation ) {
 
         Stream<PsiAnnotation> mappingAnnotations = findMappingAnnotations( owner, includeMetaAnnotations );
 
-        return Stream.concat( mappingAnnotations, mappingsAnnotations );
+        return Stream.concat( mappingAnnotations, mappingsAnnotations ).distinct();
```
Comment (filiphr) [inline src/main/java/org/mapstruct/intellij/util/MapstructAnnotationUtils.java:317]: Why is this needed? How can we have duplicates at this point?

File: src/test/java/org/mapstruct/intellij/bugs/_148/AutoInheritConfigurationTest.java [hunk 2]
```diff
@@ -0,0 +1,76 @@
+/*
+ * Copyright MapStruct Authors.
+ *
+ * Licensed under the Apache License version 2.0, available at https://www.apache.org/licenses/LICENSE-2.0
+ */
+package org.mapstruct.intellij.bugs._148;
```
Comment (filiphr) [inline src/test/java/org/mapstruct/intellij/bugs/_148/AutoInheritConfigurationTest.java:6]: Is this test for #148 or for #151?

In any case I think that this should be added in the `org.mapstruct.intellij.inspection` test package. You can add a new folder in the `testData/inspection` for the auto config if you want.

File: src/test/java/org/mapstruct/intellij/inspection/WrongUsageOfMappersFactoryInspectionTest.java [hunk 3]
```diff
@@ -51,6 +51,8 @@ public void testWrongUsageOfMappersFactory() {
         myFixture.launchAction( allQuickFixes.get( 6 ) ); // Remove jsr330 componentModel
         myFixture.launchAction( allQuickFixes.get( 8 ) ); // Remove custom componentModel
 
+        assertThat( myFixture.getAllQuickFixes() ).isEmpty();
```
Comment (filiphr) [inline src/test/java/org/mapstruct/intellij/inspection/WrongUsageOfMappersFactoryInspectionTest.java:54]: Why is this needed?

File: testData/bugs/_148/CarMapperWithExplicitInheritance.java [hunk 4]
```diff
@@ -0,0 +1,73 @@
...
+}
+
+@Mapper(
+    uses = NotToBeUsedMapper.class,
+    config = AutoInheritedConfig.class,
+    mappingInheritanceStrategy = MappingInheritanceStrategy.EXPLICIT
+)
+abstract class CarMapperWithExplicitInheritance {
+    public static final CarMapperWithExplicitInheritance INSTANCE =
+        Mappers.getMapper( CarMapperWithExplicitInheritance.class );
```
Comment (filiphr) [inline testData/bugs/_148/CarMapperWithExplicitInheritance.java:32]: Do we need this for the tests here?

File: testData/bugs/_148/MapstructIssue2318Mapper.java [hunk 5]
```diff
@@ -0,0 +1,113 @@
...
+import org.mapstruct.InheritConfiguration;
+import org.mapstruct.Mapper;
+import org.mapstruct.MapperConfig;
+import org.mapstruct.Mapping;
+import org.mapstruct.factory.Mappers;;
+
+@Mapper(config = Issue2318Mapper.Config.class)
+interface Issue2318Mapper {
+
+    Issue2318Mapper INSTANCE = Mappers.getMapper( Issue2318Mapper.class );
```
Comment (filiphr) [inline testData/bugs/_148/MapstructIssue2318Mapper.java:15]: I don't think that this is needed for the plugin tests.

File: src/main/java/org/mapstruct/intellij/inspection/UnmappedTargetPropertiesInspection.java [hunk 6]
```diff
@@ -181,6 +190,14 @@ private static boolean isBeanMappingIgnoreByDefault(PsiMethod method) {
             return false;
         }
 
+        private static boolean isPrototypeMethod(@NotNull PsiMethod method) {
+
+            return Optional.ofNullable( method.getContainingClass() )
+                .map( containingClass -> findAnnotation( containingClass, MAPPER_CONFIG_ANNOTATION_FQN ) )
+                .stream().findFirst()
+                .isPresent();
```
Comment (filiphr) [inline src/main/java/org/mapstruct/intellij/inspection/UnmappedTargetPropertiesInspection.java:198]: Can't this be replaced with `findMapperConfigClass( method.getContainingClass() ).isPresent()`

**Review by filiphr — COMMENTED** [review]
Thanks for your work on this @thunderhook.

I've been away on holidays, so only getting the time now to have a look at this.

The code looks OK to me. I've left some questions I had as comments. I'll play around a bit to see how it behaves in an actual project as well.

File: src/main/java/org/mapstruct/intellij/util/MapstructAnnotationUtils.java (hunk 1 above)
Comment (thunderhook) [reply src/main/java/org/mapstruct/intellij/util/MapstructAnnotationUtils.java:317]: During working on this, I rewrote the logic a couple of times. Inside a debugging breakpoint I stumbled accross duplicates.
So this could be a leftover of a wrong implementation approach. But to be on the safe side, I will have another look.

But somewhere there must be a cause for duplicates. Because I had to change the logic of the candidate selection to a `HashSet` instead of an `ArrayList` ([here](https://github.com/mapstruct/mapstruct-idea/pull/152/files#diff-aad0b23f58d136bb1c125a22f4ddfcf83d07fe3b6ead490249a9e8465980b3c5R210)).

When I find the culprit, I will change it back again to an ArrayList.

File: src/test/java/org/mapstruct/intellij/bugs/_148/AutoInheritConfigurationTest.java (hunk 2 above)
Comment (thunderhook) [reply src/test/java/org/mapstruct/intellij/bugs/_148/AutoInheritConfigurationTest.java:6]: Sounds good, will do! I created that package and test even before creating an issue in the github repo, so 148 was a placeholder at that point.

File: src/test/java/org/mapstruct/intellij/inspection/WrongUsageOfMappersFactoryInspectionTest.java (hunk 3 above)
Comment (thunderhook) [reply src/test/java/org/mapstruct/intellij/inspection/WrongUsageOfMappersFactoryInspectionTest.java:54]: I forgot to mention it, sorry, could've left a comment. This is a workaround for the latest EAP Intellij. The test assertion just fails and only there, and only this test. I have no Idea why.

During inspecting it inside the debugger, and after evaluating `myFixture.getAllQuickFixes()` the assertion suddenly worked. So this is a workaround for that flaky test (or flaky fixture/assertion) - I will leave a comment with a TODO there, I don't think you have the time desire and to investigate this? 😅

**Comment by thunderhook** [comment]
Thank you for having a look at the PR @filiphr. I hope you had a great and relaxing vacation!
If you find any problems during testing this on some real world problems, let me know.
I made some random checks on the Mappers inside the tests of the Mapstruct main project. There I stumbled accross the issue with referenced mappers. 🙂

I will resolve your comments and questions in the evening. 👍

File: src/main/java/org/mapstruct/intellij/inspection/UnmappedTargetPropertiesInspection.java (hunk 6 above)
Comment (thunderhook) [reply src/main/java/org/mapstruct/intellij/inspection/UnmappedTargetPropertiesInspection.java:198]: Good idea, but actually not. `findMapperConfigClass(@NotNull PsiAnnotation mapperAnnotation)` takes the mapper annotation as parameter, finds the declared attribute of `@Mapper( config = ... )` and resolves that class.

In this case the prototype-method check searches if the containing class is annotated with `@MapperConfig`:

```java
@MapperConfig
public interface MyConfig {

  // these are allowed to be incomplete, therefore disable the inspection
  Target map(Source source);

}
```

I could make this more expressive by using another method like this (or rename it):

```java
        private static boolean isPrototypeMethod(@NotNull PsiMethod method) {

            return isContainedInsideMapperConfig( method );
        }

        private static boolean isContainedInsideMapperConfig(@NotNull PsiMethod method) {

            return Optional.ofNullable( method.getContainingClass() )
                .map( containingClass -> findAnnotation( containingClass, MAPPER_CONFIG_ANNOTATION_FQN ) )
                .stream().findFirst()
                .isPresent();
        }
```

Comment (filiphr) [reply src/main/java/org/mapstruct/intellij/inspection/UnmappedTargetPropertiesInspection.java:203]: You are indeed right. Looking at our codebase I think that we already have something in `MapStuctUtil` see `MapStructUtil#isMapperConfig`. 

In any case, I would propose an alternative solution. Instead of checking if a method is prototype method. We should check if a method is in a mapper instead (see `MapStructUtil#isMapper`). There are people for some reason that use `@Mapper` and `@MapperConfig` on the same interface. We can do this check even before we get the target type.

File: src/test/java/org/mapstruct/intellij/inspection/WrongUsageOfMappersFactoryInspectionTest.java (hunk 3 above)
Comment (filiphr) [reply src/test/java/org/mapstruct/intellij/inspection/WrongUsageOfMappersFactoryInspectionTest.java:58]: >I will leave a comment with a TODO there, I don't think you have the time desire and to investigate this? 

I am a bit busy yes, but I would prefer to figure out why is it happening, since it might be happening in the actual EAP as well. Can you please extract this change into a different PR so I can investigate it?

File: src/main/java/org/mapstruct/intellij/util/MapstructAnnotationUtils.java [hunk 7]
```diff
@@ -320,19 +320,15 @@ else if ( mappingsValue instanceof PsiAnnotation ) {
...
+            return findMetaAnnotations( method, new HashSet<>() ).stream();
         }
 
-        Stream<PsiAnnotation> directAnnotations = Stream.of( method.getModifierList() )
+        return Stream.of( method.getModifierList() )
             .filter( Objects::nonNull )
             .flatMap( psiModifierList -> Arrays.stream( psiModifierList.getAnnotations() ) )
             .filter( MapstructAnnotationUtils::isMappingAnnotation );
-
-        return Stream.concat( directAnnotations, metaAnnotations );
```
Comment (filiphr) [inline src/main/java/org/mapstruct/intellij/util/MapstructAnnotationUtils.java:335]: Why are this changes needed? I need to double check how we are doing it in the processor. However, meta annotations should be merged with the direct annotations.

e.g.

```java
@Mapping(target = "fromMeta", ignore = true)
public @interface MyCustomMapping {}

@Mapper
public interface MyMapper {

    @MyCustomMapping
    @Mapping(target = "fromMethod", ignore = true)
    Target map(Source source);
}
```

The available annotations for the method is the explicit `@Mapping` on it and all the ones in the `@MyCustomMapping`. Strange, how no tests are failing.

**Review by filiphr — CHANGES_REQUESTED** [review]
Thanks for your additional changes @thunderhook.

I've replied to some of the comments and there is one more change that I think we should address.

File: src/main/java/org/mapstruct/intellij/util/MapstructAnnotationUtils.java (hunk 7 above)
Comment (thunderhook) [reply src/main/java/org/mapstruct/intellij/util/MapstructAnnotationUtils.java:335]: This is where the duplicates came from. The method `findMetaAnnotations` finds the direct mappings *and* the meta mappings. Therefore with mapstruct version 1.4+ I'm only calling this to prevent duplicates.

So the merging of direct and meta mappings are getting merged in this method.

File: src/test/java/org/mapstruct/intellij/inspection/WrongUsageOfMappersFactoryInspectionTest.java (hunk 3 above)
Comment (thunderhook) [reply src/test/java/org/mapstruct/intellij/inspection/WrongUsageOfMappersFactoryInspectionTest.java:58]: The error is only happening in the LATEST-EAP-SNAPSHOT. See: https://github.com/mapstruct/mapstruct-idea/actions/runs/6129983187
And this is also happening in the master branch.
So you can just reproduce this by changing the ideaVersion (see git patch, no separate PR needed 🙂 )

I applied this workaround to get the build green. I can of course revert the workaround and we can merge the PR although the build is failing (when all issues are resolved ofc).

```
Subject: [PATCH] change current build to LATEST-EAP-SNAPSHOT
---
Index: gradle.properties
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>ISO-8859-1
===================================================================
diff --git a/gradle.properties b/gradle.properties
--- a/gradle.properties	(revision 5168fbab259c968771f2944a98eb0187b55f5ade)
+++ b/gradle.properties	(date 1694897260461)
@@ -2,10 +2,10 @@
 # https://www.jetbrains.com/intellij-repository/releases
 # https://www.jetbrains.com/intellij-repository/snapshots
 
-ideaVersion = 2021.2
+ideaVersion = LATEST-EAP-SNAPSHOT
 ideaType = IC
 sources = true
-isEAP = false
+isEAP = true
 runGenerators = true
 
 pluginGroup = org.mapstruct

```

File: src/main/java/org/mapstruct/intellij/util/MapstructAnnotationUtils.java (hunk 7 above)
Comment (thunderhook) [reply src/main/java/org/mapstruct/intellij/util/MapstructAnnotationUtils.java]: I now renamed the method to `findDirectAndMetaAnnotations`. Initially I named it only `findMetaAnnotations` because I followed the naming of `MetaAnnotationUtil#findMetaAnnotations` which was not sufficient for us to use.

File: src/main/java/org/mapstruct/intellij/inspection/UnmappedTargetPropertiesInspection.java (hunk 6 above)
Comment (thunderhook) [reply src/main/java/org/mapstruct/intellij/inspection/UnmappedTargetPropertiesInspection.java]: Very good. I changed it as you proposed. This also avoids some unnecessary compuations.

**Comment by thunderhook** [comment]
@filiphr You can now have another look at the PR when you find time. Thanks alot!

-----

Sidenote: Reached out to you by mail. Maybe check your spam folder, because I used an emoji in the subject... 🤦 😅

File: src/main/java/org/mapstruct/intellij/util/MapstructAnnotationUtils.java (hunk 7 above)
Comment (filiphr) [reply src/main/java/org/mapstruct/intellij/util/MapstructAnnotationUtils.java]: Good point. I didn't analyse the method that well, I was mostly looking at the namings. Good idea for changing the name of the method. Now it correctly shows the intention of it.

**Comment by filiphr** [comment]
Thanks a lot for the improvements you did for the configuration inheritance.
