### PR TITLE
#159 support fluent setters with super types (e.g. lomboks @SuperBuilder)

### LINKED ISSUE #159: Code completion doesn't work with lombok @SuperBuilder annotation
### Plugin Information
- Plugin Version: 1.6.1
- Mapstruct Version: 1.5.5
- Lombok Version: 1.18.28
- Java Version: 17
- IDE Version: Intellij IDEA Ultimate 2023.2.5

### Problem Description
The code completion feature of the MapStruct Support plugin is not working properly when using the lombok `@SuperBuilder` (`lombok.experimental.SuperBuilder`) annotation.

### Steps to Reproduce
1. Create a new Java class.
2. Add the lombok `@SuperBuilder` annotation to the class.
3. Try to use code completion for any field in `@Mapper` annotation. 

### Expected Behavior
When using the `@SuperBuilder` annotation, the code completion feature should suggest the available fields.

### Actual Behavior
The code completion feature does not suggest any fields or methods.

### Screenshots and Code Snippets
```java
// Class with annotation
@Getter
@Setter
@SuperBuilder
@NoArgsConstructor
public class Builder {
    private Integer bar;
}
```
```java
// Class without annotation
@Getter
@Setter
public class WithoutBuilder {
    private Integer foo;
    private Builder innerBuilder; // To show that autocompletion works for inner builders
}
```
```java
// Mapper with broken code completion
@Mapper
public interface BuilderMapper {
    @Mapping(target = "", source = "")
    Builder map(WithoutBuilder builder);
}
```
Doesn't work for class with `@SuperBuilder`:
image
But works for class without `@SuperBuilder`:
image
Even works for class with `@SuperBuilder` which inside a class without `@SuperBuilder`:
image

### Additional Information
Generated class for `@Mapping(target = "bar", source = "foo")` to show that it is valid mapper:
```java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2023-11-13T17:06:33+0700",
    comments = "version: 1.5.5.Final, compiler: javac, environment: Java 17.0.8 (BellSoft)"
)
public class BuilderMapperImpl implements BuilderMapper {

    @Override
    public Builder map(WithoutBuilder builder) {
        if ( builder == null ) {
            return null;
        }

        Builder builder1 = new Builder();

        builder1.setBar( builder.getFoo() );

        return builder1;
    }
}

```

### PR DESCRIPTION
**Pull request by thunderhook**
I hope this change has no unwanted side effects. It checks whether a fluent setters return type also can be assigned to one of its super types to support classes like this:
```java
public static abstract class TargetBuilder<C extends Target, B extends TargetBuilder<C, B>> {

            private String testName;

            public B testName(String testName) {
                this.testName = testName;
                return self();
            }
            // ...
}
```

Fixes #159

### CODE REVIEW

**Comment by filiphr** [comment]
Check my comment in https://github.com/mapstruct/mapstruct-idea/issues/159#issuecomment-1826883528. Is the test code working even properly with the MapStruct processor. We don't really support `@SuperBuilder` from Lombok, so the fix here will be a bit misleading.

**Comment by thunderhook** [comment]
@filiphr Could you please have another look? I think it is now valid to support super types like this in the IDE plugin.
The example using in the test has the same structure as provided in https://github.com/mapstruct/mapstruct/issues/3524, see https://github.com/mapstruct/mapstruct/pull/3542/files

File: src/main/java/org/mapstruct/intellij/util/MapstructUtil.java [hunk 1]
```diff
@@ -200,17 +201,35 @@ private static boolean isPublic(@NotNull PsiField field) {
...
+        if ( returnType == null ) {
+            return false;
+        }
+
+        if ( isAssignableFrom( psiType, returnType ) ) {
+            return true;
+        }
+
+        return Arrays.stream( returnType.getSuperTypes() )
+            .anyMatch( superType -> isAssignableFrom( psiType, superType ) );
```
Comment (filiphr) [inline src/main/java/org/mapstruct/intellij/util/MapstructUtil.java:225]: There is no need to create a stream and then use `anyMatch`. Let's just iterate through the `returnType.getSuperTypes()` and do a check in the for loop.

File: src/main/java/org/mapstruct/intellij/util/MapstructUtil.java [hunk 2]
```diff
@@ -200,17 +201,35 @@ private static boolean isPublic(@NotNull PsiField field) {
...
-            TypeConversionUtil.isAssignable(
-                psiType,
-                PsiUtil.resolveGenericsClassInType( psiType ).getSubstitutor().substitute( method.getReturnType() )
-            );
+            isAssignableFromReturnTypeOrSuperTypes( psiType, method.getReturnType() );
+    }
+
+    private static boolean isAssignableFromReturnTypeOrSuperTypes(PsiType psiType, @Nullable PsiType returnType) {
+
+        if ( returnType == null ) {
```
Comment (filiphr) [inline src/main/java/org/mapstruct/intellij/util/MapstructUtil.java:216]: The `returnType` cannot be `null` because in `isFluentSetter` we are checking `method.getReturnType() != null`.

**Review by filiphr — COMMENTED** [review]
Looks good @thunderhook, I've added some small comments

**Comment by thunderhook** [comment]
@filiphr Thanks for the feedback. I have made the requested changes.
